#
# 
#
# Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
#
require 'json'

# adding necessary json serialization methods to standard classes.
class Object
  def to_jaxb_json_hash
    return self
  end
  def self.from_json o
    return o
  end
end

class String
  def self.from_json o
    return o
  end
end

class Boolean
  def self.from_json o
    return o
  end
end

class Numeric
  def self.from_json o
    return o
  end
end

class Time
  #json time is represented as number of milliseconds since epoch
  def to_jaxb_json_hash
    return (to_i * 1000) + (usec / 1000)
  end
  def self.from_json o
    if o.nil?
      return nil
    else
      return Time.at(o / 1000, (o % 1000) * 1000)
    end
  end
end

class Array
  def to_jaxb_json_hash
    a = Array.new
    each { | _item | a.push _item.to_jaxb_json_hash }
    return a
  end
end

class Hash
  def to_jaxb_json_hash
    h = Hash.new
    each { | _key, _value | h[_key.to_jaxb_json_hash] = _value.to_jaxb_json_hash }
    return h
  end
end

module EnunciateHelpers
  LAMB_CLASS_AWARE = ->(_item) do
    java_clazz = _item['@class']
    clazz_array_parts = java_clazz.split('.')
    short_clazz = clazz_array_parts.pop
    clazz_package = clazz_array_parts.map do |e| e[0] = e.first.capitalize; e end.join("::")
    clazz = clazz_package + "::" + short_clazz
    Object.const_get(clazz).send(:from_json, _item)
  end
end


module Com

module Course_genie

module Assessment

  # (no documentation provided)
  class Assessment 


    # the json hash for this Assessment
    def to_jaxb_json_hash
      _h = {}
      return _h
    end

    # the json (string form) for this Assessment
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this Assessment with a json hash
    def init_jaxb_json_hash(_o)
    end

    # constructs a Assessment from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Book

  # (no documentation provided)
  class BookDTO 

    # (no documentation provided)
    attr_accessor :id
    # (no documentation provided)
    attr_accessor :isbn
    # (no documentation provided)
    attr_accessor :title
    # (no documentation provided)
    attr_accessor :url
    # (no documentation provided)
    attr_accessor :sectionIds
    # (no documentation provided)
    attr_accessor :requiredReading
    # (no documentation provided)
    attr_accessor :suggestedReading

    # the json hash for this BookDTO
    def to_jaxb_json_hash
      _h = {}
      _h['id'] = id.to_jaxb_json_hash unless id.nil?
      _h['isbn'] = isbn.to_jaxb_json_hash unless isbn.nil?
      _h['title'] = title.to_jaxb_json_hash unless title.nil?
      _h['url'] = url.to_jaxb_json_hash unless url.nil?
      if !sectionIds.nil?
        _ha = Array.new
        sectionIds.each { | _item | _ha.push _item.to_jaxb_json_hash }
        _h['sectionIds'] = _ha
      end
      _h['requiredReading'] = requiredReading.to_jaxb_json_hash unless requiredReading.nil?
      _h['suggestedReading'] = suggestedReading.to_jaxb_json_hash unless suggestedReading.nil?
      return _h
    end

    # the json (string form) for this BookDTO
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this BookDTO with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['id'].nil?
          _oa = _o['id']
            if(_oa.is_a? Hash)
              @id = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @id =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @id = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @id.push Bignum.from_json(_item)
                 else
                   @id.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @id = _oa
            end
          end
        if !_o['isbn'].nil?
          _oa = _o['isbn']
            if(_oa.is_a? Hash)
              @isbn = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @isbn =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @isbn = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @isbn.push String.from_json(_item)
                 else
                   @isbn.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @isbn = _oa
            end
          end
        if !_o['title'].nil?
          _oa = _o['title']
            if(_oa.is_a? Hash)
              @title = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @title =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @title = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @title.push String.from_json(_item)
                 else
                   @title.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @title = _oa
            end
          end
        if !_o['url'].nil?
          _oa = _o['url']
            if(_oa.is_a? Hash)
              @url = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @url =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @url = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @url.push String.from_json(_item)
                 else
                   @url.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @url = _oa
            end
          end
        if !_o['sectionIds'].nil?
          _oa = _o['sectionIds']
            if(_oa.is_a? Hash)
              @sectionIds = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @sectionIds =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @sectionIds = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @sectionIds.push Bignum.from_json(_item)
                 else
                   @sectionIds.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @sectionIds = _oa
            end
          end
        if !_o['requiredReading'].nil?
          _oa = _o['requiredReading']
            if(_oa.is_a? Hash)
              @requiredReading = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @requiredReading =  Boolean.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @requiredReading = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @requiredReading.push Boolean.from_json(_item)
                 else
                   @requiredReading.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @requiredReading = _oa
            end
          end
        if !_o['suggestedReading'].nil?
          _oa = _o['suggestedReading']
            if(_oa.is_a? Hash)
              @suggestedReading = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @suggestedReading =  Boolean.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @suggestedReading = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @suggestedReading.push Boolean.from_json(_item)
                 else
                   @suggestedReading.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @suggestedReading = _oa
            end
          end
    end

    # constructs a BookDTO from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Syllabus

  # (no documentation provided)
  class SyllabusDTO 

    # (no documentation provided)
    attr_accessor :content
    # (no documentation provided)
    attr_accessor :sectionId
    # (no documentation provided)
    attr_accessor :syllabusId

    # the json hash for this SyllabusDTO
    def to_jaxb_json_hash
      _h = {}
      _h['content'] = content.to_jaxb_json_hash unless content.nil?
      _h['sectionId'] = sectionId.to_jaxb_json_hash unless sectionId.nil?
      _h['syllabusId'] = syllabusId.to_jaxb_json_hash unless syllabusId.nil?
      return _h
    end

    # the json (string form) for this SyllabusDTO
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this SyllabusDTO with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['content'].nil?
          _oa = _o['content']
            if(_oa.is_a? Hash)
              @content = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @content =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @content = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @content.push String.from_json(_item)
                 else
                   @content.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @content = _oa
            end
          end
        if !_o['sectionId'].nil?
          _oa = _o['sectionId']
            if(_oa.is_a? Hash)
              @sectionId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @sectionId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @sectionId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @sectionId.push Bignum.from_json(_item)
                 else
                   @sectionId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @sectionId = _oa
            end
          end
        if !_o['syllabusId'].nil?
          _oa = _o['syllabusId']
            if(_oa.is_a? Hash)
              @syllabusId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @syllabusId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @syllabusId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @syllabusId.push Bignum.from_json(_item)
                 else
                   @syllabusId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @syllabusId = _oa
            end
          end
    end

    # constructs a SyllabusDTO from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Student

  # (no documentation provided)
  class StudentDTO 

    # (no documentation provided)
    attr_accessor :email
    # (no documentation provided)
    attr_accessor :lastName
    # (no documentation provided)
    attr_accessor :studentId
    # (no documentation provided)
    attr_accessor :firstName

    # the json hash for this StudentDTO
    def to_jaxb_json_hash
      _h = {}
      _h['email'] = email.to_jaxb_json_hash unless email.nil?
      _h['lastName'] = lastName.to_jaxb_json_hash unless lastName.nil?
      _h['studentId'] = studentId.to_jaxb_json_hash unless studentId.nil?
      _h['firstName'] = firstName.to_jaxb_json_hash unless firstName.nil?
      return _h
    end

    # the json (string form) for this StudentDTO
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this StudentDTO with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['email'].nil?
          _oa = _o['email']
            if(_oa.is_a? Hash)
              @email = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @email =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @email = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @email.push String.from_json(_item)
                 else
                   @email.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @email = _oa
            end
          end
        if !_o['lastName'].nil?
          _oa = _o['lastName']
            if(_oa.is_a? Hash)
              @lastName = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @lastName =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @lastName = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @lastName.push String.from_json(_item)
                 else
                   @lastName.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @lastName = _oa
            end
          end
        if !_o['studentId'].nil?
          _oa = _o['studentId']
            if(_oa.is_a? Hash)
              @studentId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @studentId =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @studentId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @studentId.push String.from_json(_item)
                 else
                   @studentId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @studentId = _oa
            end
          end
        if !_o['firstName'].nil?
          _oa = _o['firstName']
            if(_oa.is_a? Hash)
              @firstName = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @firstName =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @firstName = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @firstName.push String.from_json(_item)
                 else
                   @firstName.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @firstName = _oa
            end
          end
    end

    # constructs a StudentDTO from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Security

  # (no documentation provided)
  class AuthQuery 

    # (no documentation provided)
    attr_accessor :password
    # (no documentation provided)
    attr_accessor :username

    # the json hash for this AuthQuery
    def to_jaxb_json_hash
      _h = {}
      _h['password'] = password.to_jaxb_json_hash unless password.nil?
      _h['username'] = username.to_jaxb_json_hash unless username.nil?
      return _h
    end

    # the json (string form) for this AuthQuery
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this AuthQuery with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['password'].nil?
          _oa = _o['password']
            if(_oa.is_a? Hash)
              @password = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @password =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @password = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @password.push String.from_json(_item)
                 else
                   @password.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @password = _oa
            end
          end
        if !_o['username'].nil?
          _oa = _o['username']
            if(_oa.is_a? Hash)
              @username = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @username =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @username = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @username.push String.from_json(_item)
                 else
                   @username.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @username = _oa
            end
          end
    end

    # constructs a AuthQuery from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Course

  # (no documentation provided)
  class CourseDTO 

    # (no documentation provided)
    attr_accessor :courseId
    # (no documentation provided)
    attr_accessor :code
    # (no documentation provided)
    attr_accessor :credits
    # (no documentation provided)
    attr_accessor :sections
    # (no documentation provided)
    attr_accessor :description
    # (no documentation provided)
    attr_accessor :name
    # (no documentation provided)
    attr_accessor :clos

    # the json hash for this CourseDTO
    def to_jaxb_json_hash
      _h = {}
      _h['courseId'] = courseId.to_jaxb_json_hash unless courseId.nil?
      _h['code'] = code.to_jaxb_json_hash unless code.nil?
      _h['credits'] = credits.to_jaxb_json_hash unless credits.nil?
      if !sections.nil?
        _ha = Array.new
        sections.each { | _item | _ha.push _item.to_jaxb_json_hash }
        _h['sections'] = _ha
      end
      _h['description'] = description.to_jaxb_json_hash unless description.nil?
      _h['name'] = name.to_jaxb_json_hash unless name.nil?
      if !clos.nil?
        _ha = Array.new
        clos.each { | _item | _ha.push _item.to_jaxb_json_hash }
        _h['clos'] = _ha
      end
      return _h
    end

    # the json (string form) for this CourseDTO
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this CourseDTO with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['courseId'].nil?
          _oa = _o['courseId']
            if(_oa.is_a? Hash)
              @courseId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @courseId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @courseId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @courseId.push Bignum.from_json(_item)
                 else
                   @courseId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @courseId = _oa
            end
          end
        if !_o['code'].nil?
          _oa = _o['code']
            if(_oa.is_a? Hash)
              @code = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @code =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @code = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @code.push String.from_json(_item)
                 else
                   @code.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @code = _oa
            end
          end
        if !_o['credits'].nil?
          _oa = _o['credits']
            if(_oa.is_a? Hash)
              @credits = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @credits =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @credits = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @credits.push String.from_json(_item)
                 else
                   @credits.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @credits = _oa
            end
          end
        if !_o['sections'].nil?
          _oa = _o['sections']
            if(_oa.is_a? Hash)
              @sections = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @sections =  Com::Course_genie::Section::SectionDTO.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @sections = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @sections.push Com::Course_genie::Section::SectionDTO.from_json(_item)
                 else
                   @sections.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @sections = _oa
            end
          end
        if !_o['description'].nil?
          _oa = _o['description']
            if(_oa.is_a? Hash)
              @description = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @description =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @description = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @description.push String.from_json(_item)
                 else
                   @description.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @description = _oa
            end
          end
        if !_o['name'].nil?
          _oa = _o['name']
            if(_oa.is_a? Hash)
              @name = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @name =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @name = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @name.push String.from_json(_item)
                 else
                   @name.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @name = _oa
            end
          end
        if !_o['clos'].nil?
          _oa = _o['clos']
            if(_oa.is_a? Hash)
              @clos = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @clos =  Com::Course_genie::Clo::CLODTO.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @clos = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @clos.push Com::Course_genie::Clo::CLODTO.from_json(_item)
                 else
                   @clos.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @clos = _oa
            end
          end
    end

    # constructs a CourseDTO from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Assessment

  # (no documentation provided)
  class AssessmentDTO 

    # (no documentation provided)
    attr_accessor :maxPoints
    # (no documentation provided)
    attr_accessor :sectionId
    # (no documentation provided)
    attr_accessor :shortName
    # (no documentation provided)
    attr_accessor :clos
    # (no documentation provided)
    attr_accessor :name
    # (no documentation provided)
    attr_accessor :category
    # (no documentation provided)
    attr_accessor :assessmentId
    # (no documentation provided)
    attr_accessor :week

    # the json hash for this AssessmentDTO
    def to_jaxb_json_hash
      _h = {}
      _h['maxPoints'] = maxPoints.to_jaxb_json_hash unless maxPoints.nil?
      _h['sectionId'] = sectionId.to_jaxb_json_hash unless sectionId.nil?
      _h['shortName'] = shortName.to_jaxb_json_hash unless shortName.nil?
      if !clos.nil?
        _ha = Array.new
        clos.each { | _item | _ha.push _item.to_jaxb_json_hash }
        _h['clos'] = _ha
      end
      _h['name'] = name.to_jaxb_json_hash unless name.nil?
      _h['category'] = category.to_jaxb_json_hash unless category.nil?
      _h['assessmentId'] = assessmentId.to_jaxb_json_hash unless assessmentId.nil?
      _h['week'] = week.to_jaxb_json_hash unless week.nil?
      return _h
    end

    # the json (string form) for this AssessmentDTO
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this AssessmentDTO with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['maxPoints'].nil?
          _oa = _o['maxPoints']
            if(_oa.is_a? Hash)
              @maxPoints = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @maxPoints =  Fixnum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @maxPoints = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @maxPoints.push Fixnum.from_json(_item)
                 else
                   @maxPoints.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @maxPoints = _oa
            end
          end
        if !_o['sectionId'].nil?
          _oa = _o['sectionId']
            if(_oa.is_a? Hash)
              @sectionId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @sectionId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @sectionId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @sectionId.push Bignum.from_json(_item)
                 else
                   @sectionId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @sectionId = _oa
            end
          end
        if !_o['shortName'].nil?
          _oa = _o['shortName']
            if(_oa.is_a? Hash)
              @shortName = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @shortName =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @shortName = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @shortName.push String.from_json(_item)
                 else
                   @shortName.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @shortName = _oa
            end
          end
        if !_o['clos'].nil?
          _oa = _o['clos']
            if(_oa.is_a? Hash)
              @clos = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @clos =  Com::Course_genie::Clo::CLODTO.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @clos = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @clos.push Com::Course_genie::Clo::CLODTO.from_json(_item)
                 else
                   @clos.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @clos = _oa
            end
          end
        if !_o['name'].nil?
          _oa = _o['name']
            if(_oa.is_a? Hash)
              @name = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @name =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @name = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @name.push String.from_json(_item)
                 else
                   @name.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @name = _oa
            end
          end
        if !_o['category'].nil?
          _oa = _o['category']
            if(_oa.is_a? Hash)
              @category = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @category =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @category = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @category.push String.from_json(_item)
                 else
                   @category.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @category = _oa
            end
          end
        if !_o['assessmentId'].nil?
          _oa = _o['assessmentId']
            if(_oa.is_a? Hash)
              @assessmentId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @assessmentId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @assessmentId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @assessmentId.push Bignum.from_json(_item)
                 else
                   @assessmentId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @assessmentId = _oa
            end
          end
        if !_o['week'].nil?
          _oa = _o['week']
            if(_oa.is_a? Hash)
              @week = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @week =  Fixnum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @week = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @week.push Fixnum.from_json(_item)
                 else
                   @week.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @week = _oa
            end
          end
    end

    # constructs a AssessmentDTO from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Section

  # (no documentation provided)
  class SectionDTO 

    # (no documentation provided)
    attr_accessor :teachingMethodology
    # (no documentation provided)
    attr_accessor :sectionId
    # (no documentation provided)
    attr_accessor :professorId
    # (no documentation provided)
    attr_accessor :code
    # (no documentation provided)
    attr_accessor :term
    # (no documentation provided)
    attr_accessor :configured
    # (no documentation provided)
    attr_accessor :assessments
    # (no documentation provided)
    attr_accessor :class_number
    # (no documentation provided)
    attr_accessor :courseId

    # the json hash for this SectionDTO
    def to_jaxb_json_hash
      _h = {}
      _h['teachingMethodology'] = teachingMethodology.to_jaxb_json_hash unless teachingMethodology.nil?
      _h['sectionId'] = sectionId.to_jaxb_json_hash unless sectionId.nil?
      _h['professorId'] = professorId.to_jaxb_json_hash unless professorId.nil?
      _h['code'] = code.to_jaxb_json_hash unless code.nil?
      _h['term'] = term.to_jaxb_json_hash unless term.nil?
      _h['configured'] = configured.to_jaxb_json_hash unless configured.nil?
      if !assessments.nil?
        _ha = Array.new
        assessments.each { | _item | _ha.push _item.to_jaxb_json_hash }
        _h['assessments'] = _ha
      end
      _h['class_number'] = class_number.to_jaxb_json_hash unless class_number.nil?
      _h['courseId'] = courseId.to_jaxb_json_hash unless courseId.nil?
      return _h
    end

    # the json (string form) for this SectionDTO
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this SectionDTO with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['teachingMethodology'].nil?
          _oa = _o['teachingMethodology']
            if(_oa.is_a? Hash)
              @teachingMethodology = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @teachingMethodology =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @teachingMethodology = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @teachingMethodology.push String.from_json(_item)
                 else
                   @teachingMethodology.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @teachingMethodology = _oa
            end
          end
        if !_o['sectionId'].nil?
          _oa = _o['sectionId']
            if(_oa.is_a? Hash)
              @sectionId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @sectionId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @sectionId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @sectionId.push Bignum.from_json(_item)
                 else
                   @sectionId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @sectionId = _oa
            end
          end
        if !_o['professorId'].nil?
          _oa = _o['professorId']
            if(_oa.is_a? Hash)
              @professorId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @professorId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @professorId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @professorId.push Bignum.from_json(_item)
                 else
                   @professorId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @professorId = _oa
            end
          end
        if !_o['code'].nil?
          _oa = _o['code']
            if(_oa.is_a? Hash)
              @code = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @code =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @code = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @code.push String.from_json(_item)
                 else
                   @code.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @code = _oa
            end
          end
        if !_o['term'].nil?
          _oa = _o['term']
            if(_oa.is_a? Hash)
              @term = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @term =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @term = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @term.push String.from_json(_item)
                 else
                   @term.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @term = _oa
            end
          end
        if !_o['configured'].nil?
          _oa = _o['configured']
            if(_oa.is_a? Hash)
              @configured = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @configured =  Boolean.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @configured = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @configured.push Boolean.from_json(_item)
                 else
                   @configured.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @configured = _oa
            end
          end
        if !_o['assessments'].nil?
          _oa = _o['assessments']
            if(_oa.is_a? Hash)
              @assessments = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @assessments =  Com::Course_genie::Assessment::AssessmentDTO.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @assessments = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @assessments.push Com::Course_genie::Assessment::AssessmentDTO.from_json(_item)
                 else
                   @assessments.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @assessments = _oa
            end
          end
        if !_o['class_number'].nil?
          _oa = _o['class_number']
            if(_oa.is_a? Hash)
              @class_number = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @class_number =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @class_number = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @class_number.push String.from_json(_item)
                 else
                   @class_number.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @class_number = _oa
            end
          end
        if !_o['courseId'].nil?
          _oa = _o['courseId']
            if(_oa.is_a? Hash)
              @courseId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @courseId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @courseId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @courseId.push Bignum.from_json(_item)
                 else
                   @courseId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @courseId = _oa
            end
          end
    end

    # constructs a SectionDTO from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Benchmark

  # (no documentation provided)
  class BenchmarkDTO 

    # (no documentation provided)
    attr_accessor :benchmarkType
    # (no documentation provided)
    attr_accessor :description
    # (no documentation provided)
    attr_accessor :benchmarkId
    # (no documentation provided)
    attr_accessor :threshold
    # (no documentation provided)
    attr_accessor :percentage

    # the json hash for this BenchmarkDTO
    def to_jaxb_json_hash
      _h = {}
      _h['benchmarkType'] = benchmarkType.to_jaxb_json_hash unless benchmarkType.nil?
      _h['description'] = description.to_jaxb_json_hash unless description.nil?
      _h['benchmarkId'] = benchmarkId.to_jaxb_json_hash unless benchmarkId.nil?
      _h['threshold'] = threshold.to_jaxb_json_hash unless threshold.nil?
      _h['percentage'] = percentage.to_jaxb_json_hash unless percentage.nil?
      return _h
    end

    # the json (string form) for this BenchmarkDTO
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this BenchmarkDTO with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['benchmarkType'].nil?
          _oa = _o['benchmarkType']
            if(_oa.is_a? Hash)
              @benchmarkType = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @benchmarkType =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @benchmarkType = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @benchmarkType.push String.from_json(_item)
                 else
                   @benchmarkType.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @benchmarkType = _oa
            end
          end
        if !_o['description'].nil?
          _oa = _o['description']
            if(_oa.is_a? Hash)
              @description = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @description =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @description = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @description.push String.from_json(_item)
                 else
                   @description.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @description = _oa
            end
          end
        if !_o['benchmarkId'].nil?
          _oa = _o['benchmarkId']
            if(_oa.is_a? Hash)
              @benchmarkId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @benchmarkId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @benchmarkId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @benchmarkId.push Bignum.from_json(_item)
                 else
                   @benchmarkId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @benchmarkId = _oa
            end
          end
        if !_o['threshold'].nil?
          _oa = _o['threshold']
            if(_oa.is_a? Hash)
              @threshold = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @threshold =  Fixnum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @threshold = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @threshold.push Fixnum.from_json(_item)
                 else
                   @threshold.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @threshold = _oa
            end
          end
        if !_o['percentage'].nil?
          _oa = _o['percentage']
            if(_oa.is_a? Hash)
              @percentage = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @percentage =  Fixnum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @percentage = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @percentage.push Fixnum.from_json(_item)
                 else
                   @percentage.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @percentage = _oa
            end
          end
    end

    # constructs a BenchmarkDTO from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Grade

  # (no documentation provided)
  class GradeDTO 

    # (no documentation provided)
    attr_accessor :studentId
    # (no documentation provided)
    attr_accessor :score
    # (no documentation provided)
    attr_accessor :gradeId
    # (no documentation provided)
    attr_accessor :assessmentId

    # the json hash for this GradeDTO
    def to_jaxb_json_hash
      _h = {}
      _h['studentId'] = studentId.to_jaxb_json_hash unless studentId.nil?
      _h['score'] = score.to_jaxb_json_hash unless score.nil?
      _h['gradeId'] = gradeId.to_jaxb_json_hash unless gradeId.nil?
      _h['assessmentId'] = assessmentId.to_jaxb_json_hash unless assessmentId.nil?
      return _h
    end

    # the json (string form) for this GradeDTO
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this GradeDTO with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['studentId'].nil?
          _oa = _o['studentId']
            if(_oa.is_a? Hash)
              @studentId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @studentId =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @studentId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @studentId.push String.from_json(_item)
                 else
                   @studentId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @studentId = _oa
            end
          end
        if !_o['score'].nil?
          _oa = _o['score']
            if(_oa.is_a? Hash)
              @score = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @score =  Float.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @score = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @score.push Float.from_json(_item)
                 else
                   @score.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @score = _oa
            end
          end
        if !_o['gradeId'].nil?
          _oa = _o['gradeId']
            if(_oa.is_a? Hash)
              @gradeId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @gradeId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @gradeId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @gradeId.push Bignum.from_json(_item)
                 else
                   @gradeId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @gradeId = _oa
            end
          end
        if !_o['assessmentId'].nil?
          _oa = _o['assessmentId']
            if(_oa.is_a? Hash)
              @assessmentId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @assessmentId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @assessmentId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @assessmentId.push Bignum.from_json(_item)
                 else
                   @assessmentId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @assessmentId = _oa
            end
          end
    end

    # constructs a GradeDTO from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Com

module Course_genie

module Clo

  # (no documentation provided)
  class CLODTO 

    # (no documentation provided)
    attr_accessor :courseId
    # (no documentation provided)
    attr_accessor :description
    # (no documentation provided)
    attr_accessor :name
    # (no documentation provided)
    attr_accessor :cloId

    # the json hash for this CLODTO
    def to_jaxb_json_hash
      _h = {}
      _h['courseId'] = courseId.to_jaxb_json_hash unless courseId.nil?
      _h['description'] = description.to_jaxb_json_hash unless description.nil?
      _h['name'] = name.to_jaxb_json_hash unless name.nil?
      _h['cloId'] = cloId.to_jaxb_json_hash unless cloId.nil?
      return _h
    end

    # the json (string form) for this CLODTO
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this CLODTO with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['courseId'].nil?
          _oa = _o['courseId']
            if(_oa.is_a? Hash)
              @courseId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @courseId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @courseId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @courseId.push Bignum.from_json(_item)
                 else
                   @courseId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @courseId = _oa
            end
          end
        if !_o['description'].nil?
          _oa = _o['description']
            if(_oa.is_a? Hash)
              @description = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @description =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @description = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @description.push String.from_json(_item)
                 else
                   @description.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @description = _oa
            end
          end
        if !_o['name'].nil?
          _oa = _o['name']
            if(_oa.is_a? Hash)
              @name = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @name =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @name = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @name.push String.from_json(_item)
                 else
                   @name.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @name = _oa
            end
          end
        if !_o['cloId'].nil?
          _oa = _o['cloId']
            if(_oa.is_a? Hash)
              @cloId = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @cloId =  Bignum.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @cloId = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @cloId.push Bignum.from_json(_item)
                 else
                   @cloId.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @cloId = _oa
            end
          end
    end

    # constructs a CLODTO from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end
